name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install gym
        pip install -r requirements.txt

    - name: 3. Ensure env.so is executable
      run: chmod +x env.cpython-38-x86_64-linux-gnu.so

    - name: 3.1 Install gdown and download weights
      run: |
        pip install gdown
        gdown https://drive.google.com/file/d/18akPkmO15bbP2fctH5xEnGSJtX4sn_1p/view?usp=drive_link
    - name: 4. Run Evaluation
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47
